name: lab_7_414816_test

on:
  push:
    branches:
      - roboczy
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install libs for testing
      run: |
        pip install pytest 
    
    - name: Prepare environment 
      run: |
        python -m pip install -r requirements.txt

    - name: Run test
      run: |
        pytest calculator_test.py
